version: "3.9"
services:
  node0:
    build: .
    container_name: sc_node0
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    networks:
      - scnetwork
    environment:
#      - FLASK_DEBUG=0
      - FIRST_NODE=true
      - NODE_NAME=node0
    command: python3 -m flask run --host=0.0.0.0
networks:
  scnetwork:
    name: scnetwork
